name = "rb-api-proxy"
main = "worker/index.js"
compatibility_date = "2026-02-24"

[[routes]]
pattern = "www.rulebritannia.org/api/*"
zone_name = "rulebritannia.org"

[[routes]]
pattern = "rulebritannia.org/api/*"
zone_name = "rulebritannia.org"
